# -Dspring.profiles.active=client_1_2
server:
  servlet:
    path: /
  port: 18081
spring:
  profiles:
    active: client-1-1
  application:
    name: client-1
    instance_id: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    #appname: client
    instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}
    # statusPageUrlPath: ${server.servlet.path}/info
    # healthCheckUrlPath: ${server.servlet.path}/health
    prefer-ip-address: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: /
#  endpoint:
#    shutdown:
#      enabled: false
---
spring:
  profiles: client-1-1
  application:
    instance_id: 1

server:
  port: 18081
---
spring:
  profiles: client-1-2
  application:
    instance_id: 2
server:
  port: 18082

---
spring:
  profiles: client-1-3
  application:
    instance_id: 3
server:
  port: 18083

    # https的设置 ssl
#    securePortEnabled: true
#    nonSecurePortEnabled: false
#    statusPageUrl: https://${eureka.hostname}/info
#    healthCheckUrl: https://${eureka.hostname}/health
#    homePageUrl: https://${eureka.hostname}/

##eureka:
  #  instance:
  #    hostname: localhost