server:
  servlet:
    path: /
  port: 18081
spring:
  profiles:
    active: dev
  application:
    name: gitconfigtest
    instance_id: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    #appname: client
    instanceId: ${spring.application.name}:${spring.application.instance_id}:${random.value}
    # statusPageUrlPath: ${server.servlet.path}/info
    # healthCheckUrlPath: ${server.servlet.path}/health
    prefer-ip-address: true

---
spring:
  profiles: dev
  application:
    instance_id: dev

server:
  port: 18081
---
spring:
  profiles: test
  application:
    instance_id: test
server:
  port: 18082

---
spring:
  profiles: prd
  application:
    instance_id: prd
server:
  port: 18083
